# Generated by Django 4.2.16 on 2024-10-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='code',
            field=models.TextField(default=''),
        ),
    ]
